# Basics
site_name: 酒井科协暑培 2023
repo_url: https://github.com/sast-summer-training-2023/sast-summer-training-2023.github.io
repo_name: SAST Summer Training 2023

theme:
  name: material
  language: zh
  custom_dir: theme/
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - content.code.annotate
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

validation:
  absolute_links: ignore
  unrecognized_links: ignore

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format

# Contents
nav:
  - 首页:
    - index.md
    - 前后端联合作业: final-hw.md
    - 资源链接: links.md
  - 基础:
    - basic/index.md
    - Linux & Git: basic/linux.md
    - Web: basic/web.md
    - 数据库 & SQL: basic/sql.md
    - Python: basic/python.md
  - AI:
    - ai/index.md
    - 数据分析 & NumPy: ai/numpy.md
    - 神经网络 & PyTorch: ai/pytorch.md
    - NLP: ai/nlp.md
    - CV: ai/cv.md
  - 后端:
    - backend/index.md
    - Django: backend/django.md
    - Rust: backend/rust.md
    - Rust Web 生态: backend/rust-web.md
    - Docker: backend/docker.md
    - 爬虫: backend/crawler.md
  - 前端:
    - frontend/index.md
    - Java: frontend/java.md
    - Android: frontend/android.md
    - JS & TS: frontend/js-ts.md
    - React: frontend/react.md
  - 游戏:
    - game/index.md
    - Unity: game/unity.md
    - 环境配置: game/env.md
